name: Build
on:
  - push
  - workflow_dispatch
jobs:
  build-arch-pkg:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - name: Install dependencies
        run: pacman --sync --refresh --sysupgrade --needed --noconfirm git python
      - name: Checkout self
        uses: actions/checkout@v4
      - id: get-info
        name: Get info
        run: python get-info.py
      - name: Checkout pkg
        run: git clone ${{ steps.get-info.outputs.url }} pkg && git -C pkg reset --hard ${{ steps.get-info.outputs.commit }}
      - name: Apply pkg patch
        run: git -C pkg apply --verbose ../patches/pkg/*.patch
      - name: Create user `build`
        run: useradd --no-create-home --shell /bin/sh build
      - name: Give user `build` sudo access
        run: 'echo "build ALL=(ALL:ALL) NOPASSWD: ALL" | tee --append /etc/sudoers'
      - name: Make `pkg` directory world-writable
        run: chmod a+w pkg
      - name: Build package
        run: 'su --command "makepkg --syncdeps --noconfirm" build'
        working-directory: pkg
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: arch-pkg
          path: pkg/*.pkg.*
    outputs:
      url: ${{ steps.get-info.outputs.url }}
      commit: ${{ steps.get-info.outputs.commit }}
  notify:
    needs: build-arch-pkg
    runs-on: ubuntu-latest
    steps:
      - name: Checkout self
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt --assume-yes install python3-git python3-python-telegram-bot
      - name: Notify
        run: python notify.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
          URL: ${{ needs.build-arch-pkg.outputs.url }}
          COMMIT: ${{ needs.build-arch-pkg.outputs.commit }}
          SUMMARY_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
