name: Build
on:
  - push
  - workflow_dispatch
jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout self
        uses: actions/checkout@v4
      - id: get-version
        name: Get version
        run: |
          set -o xtrace
          echo "version=$(cat version.txt)" >>"${GITHUB_OUTPUT}"
  build-arch-pkg:
    needs: get-version
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      env:
        VERSION: ${{ needs.get-version.outputs.version }}
      volumes:
        - /mnt:/mnt
    defaults:
      run:
        shell: bash -ex {0}
        working-directory: /mnt/work
    steps:
      - name: Create working directory
        working-directory: /mnt
        run: mkdir work
      - name: Show disk usage
        run: df --human-readable
      - name: Restore pkg cache
        uses: actions/cache/restore@v4
        with:
          path: /var/cache/pacman/pkg
          key: archlinux-pkgs-${{ github.run_id }}
          restore-keys: archlinux-pkgs-
      - name: Install dependencies
        run: pacman -Syu --noconfirm devtools git python python-tenacity
      - name: Checkout self
        run: git clone "https://github.com/${{ github.repository }}.git" /mnt/work
      - name: Prepare packages
        run: python scripts/build/prepare-packages.py
      - name: Setup makepkg.conf
        run: ln -fs /usr/share/devtools/makepkg.conf.d/x86_64.conf /etc/makepkg.conf
      - name: Get PKGBUILD
        run: pkgctl repo clone --protocol=https --switch="${VERSION}" telegram-desktop
      - name: Setup user
        run: |
          useradd builduser
          echo "builduser ALL=(ALL:ALL) NOPASSWD: ALL" >>/etc/sudoers
          chown -R builduser:builduser telegram-desktop
      - name: Build
        run: sudo -u builduser scripts/build/build.sh
      - name: Upload pkg
        uses: actions/upload-artifact@v4
        with:
          name: pkg
          path: |
            /mnt/work/telegram-desktop/*.pkg.*
            !/mnt/work/telegram-desktop/*-debug-*.pkg.*
          if-no-files-found: error
      - name: Upload debug pkg
        uses: actions/upload-artifact@v4
        with:
          name: debug-pkg
          path: /mnt/work/telegram-desktop/*-debug-*.pkg.*
      - if: success() || failure()
        name: Save pkg cache
        uses: actions/cache/save@v4
        with:
          path: /var/cache/pacman/pkg
          key: archlinux-pkgs-${{ github.run_id }}
