on:
  workflow_dispatch:
    inputs:
      repository:
        description: Repository of tdesktop
        required: true
        default: telegramdesktop/tdesktop
      version:
        description: Version of tdesktop
        required: true
        default: 3.5.0
      pkg_name:
        description: Name of Archlinux package
        required: true
        default: tdesktop-bin
jobs:
  build-tdesktop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout self
        uses: actions/checkout@v2
      - name: Checkout tdesktop
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository }}
          ref: v${{ github.event.inputs.version }}
          path: tdesktop
          submodules: recursive
      - name: Apply patches
        run: git apply --verbose ../patches/*.patch
        working-directory: tdesktop
      - name: Build docker image
        run: docker build -t tdesktop:centos_env Telegram/build/docker/centos_env/
        working-directory: tdesktop
      - name: Build tdesktop
        run: >
          docker
          run
          -v $PWD:/usr/src/tdesktop
          tdesktop:centos_env
          /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh
          -D TDESKTOP_API_ID=${{ secrets.TDESKTOP_API_ID }}
          -D TDESKTOP_API_HASH=${{ secrets.TDESKTOP_API_HASH }}
          -D DESKTOP_APP_USE_PACKAGED=OFF
          -D DESKTOP_APP_DISABLE_CRASH_REPORTS=ON
        working-directory: tdesktop
      - name: Upload tdesktop binary
        uses: actions/upload-artifact@v2
        with:
          name: tdesktop-binary
          path: tdesktop/out/Release
  build-arch-pkg:
    needs: build-tdesktop
    runs-on: ubuntu-latest
    container:
      image: archlinux
      env:
        PKG_NAME: ${{ github.event.inputs.pkg_name }}
        TDESKTOP_VERSION: ${{ github.event.inputs.version }}
    steps:
      - name: Install & update packages
        run: pacman --sync --refresh --sysupgrade --noconfirm base-devel git sudo
      - name: Checkout self
        uses: actions/checkout@v2
      - name: Download tdesktop binary
        uses: actions/download-artifact@v2
        with:
          name: tdesktop-binary
          path: arch-pkg
      - name: Create user `build`
        run: useradd --no-create-home --shell /bin/sh build
      - name: Give user `build` sudo access
        run: 'echo "build ALL=(ALL:ALL) NOPASSWD: ALL" | tee -a /etc/sudoers'
      - name: Make `arch-pkg` directory world-writable
        run: chmod a+w arch-pkg
      - name: Build package
        run: 'su --command "makepkg --syncdeps --noconfirm" build'
        working-directory: arch-pkg
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: arch-pkg
          path: arch-pkg/*.pkg.*
