name: Fetch latest release
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  fetch-latest-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - id: get-info
        name: Get info
        run: ./get-info.sh
      - id: get-latest-release
        name: Get latest release
        run: echo "version=$(curl --location --silent https://api.github.com/repos/${{ steps.get-info.outputs.repo }}/releases/latest | jq -r .tag_name | sed --regexp-extended 's/v([[:digit:]]+(\.[[:digit:]]+)+)/\1/')" >>$GITHUB_OUTPUT
      - if: steps.get-info.outputs.version != steps.get-latest-release.outputs.version
        name: Save new version
        run: jq '.version = "${{ steps.get-latest-release.outputs.version }}"' info.json >info-new.json && mv --force info-new.json info.json
      - if: steps.get-info.outputs.version != steps.get-latest-release.outputs.version
        name: Setup git
        run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - if: steps.get-info.outputs.version != steps.get-latest-release.outputs.version
        name: Commit
        run: git commit --all --message="Update version to ${{ steps.get-latest-release.outputs.version }}"
      - if: steps.get-info.outputs.version != steps.get-latest-release.outputs.version
        name: Push to GitHub
        run: git push
