name: Update
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout self
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Install dependency
        run: sudo apt-get --assume-yes install python3-git 
      - name: Check for update
        run: python update.py
